server:
  port: ${APPLICATION_PORT}
spring:
  application:
    name: auth
  mail:
    host: ${EMAIL_SERVER_HOST:test}
    port: ${EMAIL_SERVER_PORT:000}
    username: ${EMAIL_SERVER_USER:test}
    password: ${EMAIL_SERVER_PASSWORD:test}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
